export const PostActionTypes = {
  SET_POSTS: 'SET_POSTS',
  PUSH_POST: 'PUSH_POST',
  DELETE_POST: 'DELETE_POST',
  ADD_COMMENT_TO_POST: 'ADD_COMMENT_TO_POST',
  DELETE_COMMENT_FROM_POST: 'DELETE_COMMENT_FROM_POST',
  ADD_LIKE_TO_POST: 'ADD_LIKE_TO_POST',
  ADD_DISLIKE_TO_POST: 'ADD_DISLIKE_TO_POST',
  REMOVE_LIKE_FROM_POST: 'REMOVE_LIKE_FROM_POST',
  REMOVE_DISLIKE_FROM_POST: 'REMOVE_DISLIKE_FROM_POST'
};
