export const CurrentUserActionTypes = {
  RESET_CURRENT_USER_INFO: 'RESET_CURRENT_USER_INFO',
  SET_CURRENT_USER_INFO: 'SET_CURRENT_USER_INFO',
  SET_CURRENT_USER_PROFILE_PIC: 'SET_CURRENT_USER_PROFILE_PIC',
  SET_CURRENT_USER_COVER_PIC: 'SET_CURRENT_USER_COVER_PIC',
  ADD_FRIEND_TO_FRIENDLIST: 'ADD_FRIEND_TO_FRIENDLIST',
  SET_FRIENDLIST: 'SET_FRIENDLIST'
};
